# Site settings
title: Doug's Blog
description: "A minimal blog template, build with Jekyll."
url: "http://www.dougbarrett.nz/blog"
author:
  name: "Doug Barrett"
  url: "http://www.dougbarrett.nz/"

# Build settings
baseurl: "/blog"
production_url : "http://www.dougbarrett.nz/blog"
markdown: kramdown
source: .
destination: ./_site
permalink: /:title

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/:num/' # Pages are index.html inside this folder (default)

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

############################################################

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate-v2

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: true
reverse: false
