# Site settings
title: Doug's Blog
description: "A minimal blog template, build with Jekyll."
url: "http://www.dougbarrett.nz/blog"
author:
  name: "Doug Barrett"
  url: "http://www.dougbarrett.nz/"

# Build settings
baseurl: "/blog"
production_url : "http://www.dougbarrett.nz/blog"
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: true
reverse: false
